### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by dimax0220** [gwen001/s3-buckets-finder#4]
```
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/s3-buckets-finder/AmazonBucket.php:97
Stack trace:
#0 /root/s3-buckets-finder/BucketBruteForcer.php(504): AmazonBucket->exist(NULL)
#1 /root/s3-buckets-finder/BucketBruteForcer.php(370): BucketBruteForcer->testBucket('example')
#2 /root/s3-buckets-finder/BucketBruteForcer.php(340): BucketBruteForcer->loop(Array)
#3 /root/s3-buckets-finder/s3-buckets-bruteforcer.php(133): BucketBruteForcer->run()
#4 {main}
  thrown in /root/s3-buckets-finder/AmazonBucket.php on line 97
```

**Comment by gwen001** [comment]
Install curl mod for PHP.
